## Multilayer perceptron Algorytm

### Reading iris data

In [2]:
using CSV
iris = CSV.read("iris_data.csv")
println(iris)

150×6 DataFrames.DataFrame
│ Row │ Sepal Length │ Sepal Width │ Petal Length │ Petal Width │ Species         │ Class  │
│     │ Float64⍰     │ Float64⍰    │ Float64⍰     │ Float64⍰    │ String⍰         │ Int64⍰ │
├─────┼──────────────┼─────────────┼──────────────┼─────────────┼─────────────────┼────────┤
│ 1   │ 5.1          │ 3.5         │ 1.4          │ 0.2         │ Iris-setosa     │ 0      │
│ 2   │ 4.9          │ 3.0         │ 1.4          │ 0.2         │ Iris-setosa     │ 0      │
│ 3   │ 4.7          │ 3.2         │ 1.3          │ 0.2         │ Iris-setosa     │ 0      │
│ 4   │ 4.6          │ 3.1         │ 1.5          │ 0.2         │ Iris-setosa     │ 0      │
│ 5   │ 5.0          │ 3.6         │ 1.4          │ 0.2         │ Iris-setosa     │ 0      │
│ 6   │ 5.4          │ 3.9         │ 1.7          │ 0.4         │ Iris-setosa     │ 0      │
│ 7   │ 4.6          │ 3.4         │ 1.4          │ 0.3         │ Iris-setosa     │ 0      │
│ 8   │ 5.0          │ 3.4         │ 1.5   

In [3]:
X = zeros(4, 150)
Y = zeros(3, 150)

for i = 1:150
    for j = 1:4
        X[j, i] = iris[i, j]
        if iris[i , 5] == "setosa"
            Y[1, i] = 1.0
        elseif iris[i, 5] == "versicolor"
            Y[2, i] = 1.0
        else
            Y[3, i] = 1.0
        end
    end
end

In [4]:
iris[90, : ]

DataFrameRow. Omitted printing of 2 columns
│ Row │ Sepal Length │ Sepal Width │ Petal Length │ Petal Width │
│     │ Float64⍰     │ Float64⍰    │ Float64⍰     │ Float64⍰    │
├─────┼──────────────┼─────────────┼──────────────┼─────────────┤
│ 90  │ 5.5          │ 2.5         │ 4.0          │ 1.3         │

In [5]:
X[:,90]

4-element Array{Float64,1}:
 5.5
 2.5
 4.0
 1.3

In [6]:
Y[:,90]

3-element Array{Float64,1}:
 0.0
 0.0
 1.0

### Signoid, softmax and Cross entropy functions

In [7]:
# define signoid function
σ(s) = 1/(1+exp(-s))
dσ(s)= σ(s)*(1- σ(s))

# define softmax function
softmax(a,i)= exp(a[i])/(sum(exp(a[j]) for j = 1:length(a)))

# define cross entropy loss function
L(o,y)= -sum(y[i]*log(o[i]) for i= 1:length(y))
    
# define hadamard product
hadamard(x,y )=[x[i]*y[i] for i = 1:length(x)];

### Forward_propagation

In [8]:
function forward_propagation(x,y,w,b)
    a1=copy(x)
    z2=w[1]*a1+b[1]
    a2=σ-(z2)
    
    z3=w[2]*a2+b[2]
    a3=σ-(z4)
    
    z4=w(3)*a2+b[2]
    a4=σ-(z4)
    
    a=[a1,a2,a3,a4]
    z=[z1,z2,z3,z4]
    o=[softmax(a4,i) for i=1:length(a4)]
    loss=L(o,y)
    return a,z,o,loss
end

forward_propagation (generic function with 1 method)

In [9]:
forward_propagation(X[:,1],Y[:,1],w,b)

UndefVarError: UndefVarError: w not defined

### backpropagation function

In [10]:
function backpropagation(x,y,w,b)
    a,z,o,loss= forward_propagation(x,y,w,b)
    δ4= a[4]-y
    δ3= hadamard(w[3]' * δ4, dσ.(z[3]))
    δ2= hadamard(w[2]' * δ3, dσ.(z[2]))
    δ= [[0.0],δ2, δ3, δ4]
    return a, δ
end
    
    
function VL(x,y w,b)
    a,δ= backpropagation(x,y,w,b)
    db1=copy( δ[2])
    db2=copy( δ[3])
    db3=copy( δ[4])
        
    dw1=δ[2]*a[1]'
    dw2=δ[3]*a[2]'
    dw3=δ[4]*a[3]'
    return [db1,db2,db3],[dw1,dw2,dw3]
end
        
function gradient_descent(x,y,w,b,α)
            db,dw =VL(x,y,w,b)
            for i = 1:length(w)
                w[i] -= σ*dw[i]
                b[i] -= σ*b[i]
            end
end
            

LoadError: syntax: missing comma or ) in argument list

### initialize weight matrices and bias

In [11]:
# initialize weight matrix
w1= rand(5,4)
w2=rand(5,5)
w3= rand(3,5)
w=[w1,w2,w3]

#initialize bias
b1=-1*ones(5)
b2=-1*ones(5)
b3=-1*ones(3)
b=[b1,b2,b3]
for k _ =1:1000
    stochastic_gradient_descent!(x,y,w,b, .34,30)
end

LoadError: syntax: invalid iteration specification

In [12]:
train_data= zeros(4,100)
train_label= zeros(3,100)
for _ i 1:100
    j= rand(1:3)
    if j==1
        k=rand(1:50)
        train_data[:,1]=copy(x[:,k]) 
        train_label[:,1]=copy(x[:,k])
    elseif j==2
        k=rand(50:100)
        train_data[:,1]=copy(x[:,k]) 
        train_label[:,1]=copy(x[:,k])
    else
        k=rand(100:150)
        train_data[:,1]=copy(x[:,k]) 
        train_label[:,1]=copy(x[:,k])
    end
end

LoadError: syntax: invalid iteration specification

In [13]:
for_ in 1:1000000
    j= rand(1:150)
    gradient_descent!(x[:,j],y[:,j],w,b,0.67)
end

UndefVarError: UndefVarError: for_ not defined

In [14]:
forward_propagation(x[:,110],y[:,110],w,b)[3:4]

UndefVarError: UndefVarError: x not defined

In [15]:
y[:,20]

UndefVarError: UndefVarError: y not defined

In [16]:
function mini_batcg_VL(train_data, train_label,w,b,m)
    i=rand(1:100)
    
    a,δ= backpropagation(train_data[:,i,train_label[:,i], w,b)
    db1= δ[2]
    db2=δ[3]
    db3= δ[4]
        
    dw1=δ[2]*a[1]'
    dw2=δ[3]*a[2]'
    dw3=δ[4]*a[3]'
    
    for _ in 1:m
        j=rand(1:100)
        a,δ= backpropagation(train_data[:,i,train_label[:,i], w,b)
        db1+=copy( δ[2])
        db2+=copy( δ[3])
        db3+=copy( δ[4])
        
        dw1+=δ[2]*a[1]'
        dw2+=δ[3]*a[2]'
        dw3+=δ[4]*a[3]'

LoadError: syntax: missing separator in array expression

In [17]:
function stochastic_gradient_descent!(train_data,train_label,w,b,α,m)
    db,dw = mini_batch_VL(train_data,train_label,w,b,m)
    for i=1:length(w)
        w[i]-=α*dw[i]
        b[i]-=α*b[i]
    end
end

stochastic_gradient_descent! (generic function with 1 method)

In [18]:
# initialize weight 
w1= rand(5,4)
w2=rand(5,5)
w3= rand(3,5)
w=[w1,w2,w3]

#initialize bias
b1=-1*ones(5)
b2=-1*ones(5)
b3=-1*ones(3)
b=[b1,b2,b3]

3-element Array{Array{Float64,1},1}:
 [-1.0, -1.0, -1.0, -1.0, -1.0]
 [-1.0, -1.0, -1.0, -1.0, -1.0]
 [-1.0, -1.0, -1.0]            

In [19]:
for_in 1:1000000
    stochastic_gradient_descent!(train_data,train_label,w,b,.37,23)
end

LoadError: syntax: extra token "1" after end of expression

In [20]:
forward_propagation(x[:,85],y[:,85],w,b)[3:4]

UndefVarError: UndefVarError: x not defined

In [21]:
mistw1=rand(10,785)
mnistw2= rand(10,10)
w3=rand(10,10)
w=[w1,w2,w3]

3-element Array{Array{Float64,2},1}:
 [0.643358 0.350038 0.0944178 0.556408; 0.976975 0.628813 0.153914 0.101899; … ; 0.0120382 0.292837 0.158768 0.381395; 0.927875 0.154272 0.409705 0.933252]    
 [0.848299 0.6742 … 0.382498 0.218427; 0.1437 0.514645 … 0.207006 0.642408; … ; 0.707575 0.61624 … 0.325069 0.714954; 0.385892 0.446553 … 0.275021 0.408143]   
 [0.234364 0.126573 … 0.909081 0.858151; 0.3612 0.543752 … 0.0390157 0.397141; … ; 0.102323 0.421436 … 0.298539 0.38447; 0.841721 0.922551 … 0.623045 0.740245]

In [22]:
using MLDatasets

In [23]:
size

size (generic function with 110 methods)

In [24]:
train_x

UndefVarError: UndefVarError: train_x not defined